# Generated by Django 3.0.5 on 2020-07-14 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tapas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('prix', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('ordre', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('commentaires', models.TextField(blank=True, max_length=100, null=True)),
                ('langue', models.CharField(choices=[('FR', 'FR'), ('EN', 'EN')], default='FR', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TexteDePresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_de_texte', models.CharField(choices=[('RESTAURANT', 'RESTAURANT'), ('TAPAS', 'TAPAS'), ('WINE', 'VINS')], max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('langue', models.CharField(choices=[('FR', 'FR'), ('EN', 'EN')], default='FR', max_length=100)),
            ],
        ),
    ]
